include:
  - project: houxuejie/ci_templates
    ref: master
    file:
      - docker.yaml

stages:
  - build
  - deploy

build:
  stage: build
  extends: .docker:build:v2
  only:
    - tags
  tags:
    - zt
    - docker

deploy:
  stage: deploy
  only:
    - tags
  script:
    - npm publish
