include:
  - project: hushuibin/ci_templates
    ref: master
    file:
      - yarn.yaml

stages:
  - build
  - deploy

build:
  stage: build
  extends: .yarn:build
  only:
    - tags
  tags:
    - zt
    - docker
  after_script:
    - npm publish
